export const GET_CHARACTER_LIST_REQUEST = 'GET_CHARACTER_LIST_REQUEST';
export const GET_CHARACTER_LIST_SUCCESS = 'GET_CHARACTER_LIST_SUCCESS';
export const GET_CHARACTER_LIST_FAILED = 'GET_CHARACTER_LIST_FAILED';

export const SET_CURRENT_PAGE_NUMBER = 'SET_CURRENT_PAGE_NUMBER';
